class Player :
    def __init__(self) :
        self.fortune = 500000
        self.ownedBlocks = []
        self.items = []
        self.uninhabitedIsland = 0
        self.pos = 0
        self.type = 0
    def move(self,num) :
        self.pos += num
players = []